title.products=Products
message.order_complete=Thank you for your order!
error.invalid_credentials=Username and password do not match
error.locked_out=Sorry, this user has been locked out
error.username_required=Username is required
error.password_required=Password is required
